custom: ['https://deinserverhost.de/store/aff.php?aff=4224', 'https://living-bots.net/donation?key=$2y$10$TaPketuiZ5RlHfKCv9F4ieTIcEo81fzG7CCo4jQp/LRocd3dW00we', 'https://minehub.de/register/?ref=66691']
